### ISSUE TITLE
Implement tests for skin animation

### ISSUE THREAD

**Issue by stevk** [KhronosGroup/glTF-Asset-Generator#437]
**General Tasks**
- [x] Model with a T pose that is different than if the skin wasn't applied. 10 Vertices. 1.0 high 0.2 wide.
- [ ] <strike>Babylon playground for setting up test values</strike>

**Test models**
- [x] Two bones (No animation, T pose works)
- [x] Animating bones (just one transform. scale?)
- [ ] <strike>Joint weights, 3 are 0 value and the fourth is 1</strike>
- [x] Skinned mesh node with transform (skinned mesh node transform is ignored) and Skinned mesh node with parent transform (skinned mesh node parent transform)
- [x] Joint weights, 5 bones. Only four affect any given vertex.
- [ ] <strike>Partial weights on multiple joints for one vertex</strike>
- [x] Didn't specify inversebindmatrix
- [x] Two skins with hierarchy that overlaps
- [ ] <strike>Common ancestor of joints is not the root of the node</strike> This is for the skeleton property which should not be used
- [x] Multiple joints with the same parent joint
- [x] Joints with holes still work (skips a node. Skipped node is not directly affected)
- [x] Meshes in node hierarchy (Skin + Node animation) (attachments)
- [x] Joints node is not in the scene
- [ ] Joint hierarchy has no common root. (https://github.com/KhronosGroup/glTF/issues/1270)
As discussed, the skeleton property should probably be removed, and can already be ignored by implementations. In addition to that, we should have an example asset for which no common root is possible (e.g. bones form two subtrees starting from the scene root).
not skeleton property is kept.
- [ ] Multiple meshes sharing a single skin. (https://github.com/KhronosGroup/glTF/issues/1285)
- [ ] Many (>4) joint vertex influences. (https://github.com/KhronosGroup/glTF/issues/1381)

**Types test models**
- [x] Joints type (byte or short)
- [x] Weights type (float, byte, or short)

**Comment by bghgary** [comment]
#346
