### ISSUE TITLE
Add more tests for skin animation

### ISSUE THREAD

**Issue by stevk** [KhronosGroup/glTF-Asset-Generator#459]
- [ ]  Joint hierarchy has no common root. (KhronosGroup/glTF#1270)
As discussed, the skeleton property should probably be removed, and can already be ignored by implementations. In addition to that, we should have an example asset for which no common root is possible (e.g. bones form two subtrees starting from the scene root).
not skeleton property is kept.
 
- [ ] Multiple meshes sharing a single skin. (KhronosGroup/glTF#1285)
 
- [ ] Many (>4) joint vertex influences. (KhronosGroup/glTF#1381)
