### ISSUE TITLE
Prep code for Jan 2019 Hackathon

### ISSUE THREAD

**Issue by stevk** [KhronosGroup/glTF-Asset-Generator#475]
Below are the items that we want to have complete before the Hackathon, in descending priority order:

Tasks for @stevk :
- [x] Code style guide
- [x] Contributing guide
- [x] Create a ModelGroup class template
- [x] Update existing code to be compliant with the code style doc
- [x] #429 Add a Negative test flag to the manifest 
- [x] Test building the project in Visual Studio Code
- [x] #441 Make a model to handle asymmetric, non-zero tangents for cubic spline

Tasks for @kcoley :
- [x] #468 Change how the folder index is tracked so it doesn't change when model groups are inserted 
- [x] Test building the project in a Mac environment
